  # INFO: This compose file deploys the official Docker images from a stable, tested master branch
# MODIFIED: 2023-06-01
# MAINTAINER: Martin Weise <martin.weise@tuwien.ac.at>

version: "3.6"

volumes:
  metadata-db-data:
  data-db-data:
  auth-db-data:
  upload-service-data:
  search-db-data:

services:

  dbrepo-metadata-db:
    restart: "no"
    container_name: dbrepo-metadata-db
    hostname: metadata-db
    image: dbrepo/metadata-db@sha256:326adea3ed7c1a48ac53919bb912e2f33a3c2e80bff06bf703062480b792b164
    build: ./dbrepo-metadata-db
    volumes:
      - metadata-db-data:/bitnami/mariadb
      - ./dbrepo-metadata-db/setup-schema_local.sql:/docker-entrypoint-initdb.d/setup-schema_local.sql
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: "${METADATA_DB:-fda}"
      MARIADB_ROOT_PASSWORD: "${METADATA_PASSWORD:-dbrepo}"
    healthcheck:
      test: mysqladmin ping --user="${METADATA_USERNAME:-root}" --password="${METADATA_PASSWORD:-dbrepo}" --silent
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: json-file

  dbrepo-data-db:
    restart: "no"
    container_name: dbrepo-data-db
    hostname: data-db
    image: docker.io/bitnami/mariadb:10.5
    volumes:
      - data-db-data:/bitnami/mariadb
      - "${SHARED_FILESYSTEM:-/tmp}:/tmp"
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "${USER_DB_PASSWORD:-dbrepo}"
    healthcheck:
      test: mysqladmin ping --user="${USER_DB_USERNAME:-root}" --password="${USER_DB_PASSWORD:-dbrepo}" --silent
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: json-file

  dbrepo-auth-db:
    restart: "no"
    container_name: dbrepo-auth-db
    hostname: auth-db
    image: docker.io/bitnami/mariadb:10.5
    volumes:
      - auth-db-data:/bitnami/mariadb
    ports:
      - "3308:3306"
    environment:
      MARIADB_DATABASE: "${AUTH_DB:-keycloak}"
      MARIADB_ROOT_PASSWORD: "${AUTH_PASSWORD:-dbrepo}"
    healthcheck:
      test: mysqladmin ping --user="${AUTH_USERNAME:-root}" --password="${AUTH_PASSWORD:-dbrepo}" --silent
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: json-file

  dbrepo-upload-service:
    restart: "no"
    container_name: dbrepo-upload-service
    hostname: upload-service
    image: docker.io/tusproject/tusd:v1.12
    ports:
      - "1080:1080"
    command:
      - "--base-path=/api/upload/files/"
    volumes:
      - upload-service-data:/data
      - "${SHARED_FILESYSTEM:-/tmp}:/srv/tusd-data/data"
    logging:
      driver: json-file

  dbrepo-authentication-service:
    restart: "no"
    container_name: dbrepo-authentication-service
    hostname: authentication-service
    image: dbrepo/authentication-service@sha256:634e006d779650a6afb362c2d0e8d621f7d2e89f1384884542907b24bd4c6796
    build: ./dbrepo-authentication-service
    ports:
      - "8443:8443"
      - "8080:8080"
    healthcheck:
      test: curl -sSL 'http://0.0.0.0:8080/realms/dbrepo' | grep "dbrepo" || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
    environment:
      AUTH_DB: "${AUTH_DB:-keycloak}"
      KC_DB_USERNAME: "${AUTH_USERNAME:-root}"
      KC_DB_PASSWORD: "${AUTH_PASSWORD:-dbrepo}"
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN:-fda}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD:-fda}"
    depends_on:
      dbrepo-auth-db:
        condition: service_healthy
    logging:
      driver: json-file

  dbrepo-metadata-service:
    restart: "no"
    container_name: dbrepo-metadata-service
    hostname: metadata-service
    image: dbrepo/metadata-service@sha256:0e6834a2b7f2fe3036e22bcea9ff4c2c7ba03607e92e605e01254b45edb21fc8
    build: ./dbrepo-metadata-service
    volumes:
      - "${SHARED_FILESYSTEM:-/tmp}:/tmp"
    ports:
      - "9099:9099"
    environment:
      ADMIN_MAIL: "${ADMIN_MAIL:-noreply@localhost}"
      BASE_URL: "${BASE_URL:-http://localhost}"
      GRANT_PRIVILEGES: "${GRANT_PRIVILEGES:-SELECT, CREATE, CREATE VIEW, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, INDEX, TRIGGER, INSERT, UPDATE, DELETE}"
      MIN_CONCURRENT_CONSUMERS: ${MIN_CONCURRENT_CONSUMERS:-1}
      MAX_CONCURRENT_CONSUMERS: ${MAX_CONCURRENT_CONSUMERS:-5}
      BROKER_USERNAME: ${BROKER_USERNAME:-fda}
      BROKER_PASSWORD: ${BROKER_PASSWORD:-fda}
      BROKER_ENDPOINT: "${BROKER_ENDPOINT:-http://broker-service:15672/admin/broker}"
      BROKER_HOST: "${BROKER_HOST:-broker-service}"
      BROKER_VIRTUALHOST: ${BROKER_VIRTUALHOST:-dbrepo}
      REQUEUE_REJECTED: ${REQUEUE_REJECTED:-false}
      QUEUE_NAME: ${QUEUE_NAME:-dbrepo}
      EXCHANGE_NAME: ${EXCHANGE_NAME:-dbrepo}
      ROUTING_KEY: "${ROUTING_KEY:-dbrepo.#}"
      CONNECTION_TIMEOUT: ${CONNECTION_TIMEOUT:-60000}
      DELETED_RECORD: "${DELETED_RECORD:-persistent}"
      EARLIEST_DATESTAMP: "${EARLIEST_DATESTAMP:-2022-09-17T18:23:00Z}"
      GRANULARITY: "${GRANULARITY:-YYYY-MM-DDThh:mm:ssZ}"
      JWT_ISSUER: "${JWT_ISSUER:-http://localhost/api/auth/realms/dbrepo}"
      JWT_PUBKEY: "${JWT_PUBKEY:-MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqqnHQ2BWWW9vDNLRCcxD++xZg/16oqMo/c1l+lcFEjjAIJjJp/HqrPYU/U9GvquGE6PbVFtTzW1KcKawOW+FJNOA3CGo8Q1TFEfz43B8rZpKsFbJKvQGVv1Z4HaKPvLUm7iMm8Hv91cLduuoWx6Q3DPe2vg13GKKEZe7UFghF+0T9u8EKzA/XqQ0OiICmsmYPbwvf9N3bCKsB/Y10EYmZRb8IhCoV9mmO5TxgWgiuNeCTtNCv2ePYqL/U0WvyGFW0reasIK8eg3KrAUj8DpyOgPOVBn3lBGf+3KFSYi+0bwZbJZWqbC/Xlk20Go1YfeJPRIt7ImxD27R/lNjgDO/MwIDAQAB}"
      LOG_LEVEL: "${LOG_LEVEL:-debug}"
      METADATA_DB: "${METADATA_DB:-fda}"
      METADATA_HOST: "${METADATA_HOST:-metadata-db}"
      METADATA_JDBC_EXTRA_ARGS: "${METADATA_JDBC_EXTRA_ARGS:-}"
      METADATA_USERNAME: "${METADATA_USERNAME:-root}"
      METADATA_PASSWORD: "${METADATA_PASSWORD:-dbrepo}"
      NOT_SUPPORTED_KEYWORDS: "${NOT_SUPPORTED_KEYWORDS:-\\*,AVG,BIT_AND,BIT_OR,BIT_XOR,COUNT,COUNTDISTINCT,GROUP_CONCAT,JSON_ARRAYAGG,JSON_OBJECTAGG,MAX,MIN,STD,STDDEV,STDDEV_POP,STDDEV_SAMP,SUM,VARIANCE,VAR_POP,VAR_SAMP,--}"
      PID_BASE: "${PID_BASE:-http://localhost/pid/}"
      REPOSITORY_NAME: "${REPOSITORY_NAME:-Example Repository}"
      SEARCH_USERNAME: "${SEARCH_USERNAME:-admin}"
      SEARCH_PASSWORD: "${SEARCH_PASSWORD:-admin}"
      SHARED_FILESYSTEM: "${SHARED_FILESYSTEM:-/tmp}"
      DELETE_AFTER_IMPORT: "${DELETE_AFTER_IMPORT:-true}"
      USER_NETWORK: "${USER_NETWORK:-userdb}"
      WEBSITE: "${WEBSITE:-http://localhost}"
      KEYCLOAK_HOST: "${KEYCLOAK_HOST:-http://authentication-service:8080}"
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN:-fda}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD:-fda}"
      DATACITE_URL: "${DATACITE_URL:-https://api.test.datacite.org}"
      DATACITE_PREFIX: "${DATACITE_PREFIX:-}"
      DATACITE_USERNAME: "${DATACITE_USERNAME:-}"
      DATACITE_PASSWORD: "${DATACITE_PASSWORD:-}"
    healthcheck:
      test: wget -qO- localhost:9099/actuator/health/readiness | grep -q "UP" || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
    depends_on:
      dbrepo-authentication-service:
        condition: service_healthy
      dbrepo-broker-service:
        condition: service_healthy
      dbrepo-metadata-db:
        condition: service_healthy
      dbrepo-search-db:
        condition: service_healthy
    logging:
      driver: json-file

  dbrepo-analyse-service:
    restart: "no"
    container_name: dbrepo-analyse-service
    hostname: analyse-service
    image: dbrepo/analyse-service@sha256:657eb844f7d6ac65a435f0582605eb27e5ec23983e8f6fbd95dae197954db4c9 
    build: ./dbrepo-analyse-service
    ports:
      - "5000:5000"
    environment:
      SHARED_FILESYSTEM: "${SHARED_FILESYSTEM:-/tmp}"
    volumes:
      - "${SHARED_FILESYSTEM:-/tmp}:/tmp"
    healthcheck:
      test: curl -sSL localhost:5000/health | grep 'UP' || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: json-file

  dbrepo-broker-service:
    restart: "no"
    container_name: dbrepo-broker-service
    hostname: broker-service
    image: docker.io/bitnami/rabbitmq:3.10
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./dbrepo-broker-service/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./dbrepo-broker-service/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./dbrepo-broker-service/cert.pem:/app/cert.pem
      - ./dbrepo-broker-service/pubkey.pem:/app/pubkey.pem
      - ./dbrepo-broker-service/definitions.json:/app/definitions.json
    healthcheck:
      test: rabbitmq-diagnostics -q is_running | grep 'is fully booted and running'
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: json-file

  dbrepo-search-db:
    restart: "no"
    container_name: dbrepo-search-db
    hostname: search-db
    image: dbrepo/search-db@sha256:bf66ee920a1321923b2d3c90bf657f83cda6a6df9dae98cfeb69c495f10a7420
    build: ./dbrepo-search-db
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -sSL localhost:9200/_plugins/_security/health | jq .status | grep UP
      interval: 10s
      timeout: 5s
      retries: 12
    environment:
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
      logger.level: "WARN"
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - search-db-data:/usr/share/elasticsearch/data
    logging:
      driver: json-file

  dbrepo-ui:
    restart: "no"
    container_name: dbrepo-ui
    hostname: ui
    image: dbrepo/ui@sha256:a30c40610d7187adddef57e2c8d2866341aa200cd635ec54c956f50d4020ff52
    build: ./dbrepo-ui
    environment:
      BROKER_USERNAME: "${BROKER_USERNAME:-fda}"
      BROKER_PASSWORD: "${BROKER_PASSWORD:-fda}"
      BROKER_LOGIN_URL: "${BROKER_LOGIN_URL:-/admin/broker/}"
      KEYCLOAK_LOGIN_URL: "${KEYCLOAK_LOGIN_URL:-/api/auth/admin/}"
      OPENSEARCH_LOGIN_URL: "${OPENSEARCH_LOGIN_URL:-/admin/dashboard/}"
      SHARED_FILESYSTEM: "${SHARED_FILESYSTEM:-/tmp}"
      LOGO: "${LOGO:-/logo.png}"
      SEARCH_USERNAME: "${SEARCH_USERNAME:-admin}"
      SEARCH_PASSWORD: "${SEARCH_PASSWORD:-admin}"
      VERSION: "${VERSION:-latest}"
      TITLE: "${TITLE:-Database Repository}"
      ICON: "${ICON:-/favicon.ico}"
      DBREPO_CLIENT_ID: "${DBREPO_CLIENT_ID:-dbrepo-client}"
      DBREPO_CLIENT_SECRET: "${DBREPO_CLIENT_SECRET:-MUwRc7yfXSJwX8AdRMWaQC3Nep1VjwgG}"
      UPLOAD_PATH: "${UPLOAD_PATH:-/tmp/}"
      FORCE_SSL: "${FORCE_SSL:-false}"
      DOI_URL: "${DOI_URL:-https://doi.org}"
    depends_on:
      dbrepo-upload-service:
        condition: service_started
    logging:
      driver: json-file

  dbrepo-gateway-service:
    restart: "no"
    container_name: dbrepo-gateway-service
    hostname: gateway-service
    image: docker.io/nginx:1.25-alpine-slim
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dbrepo-gateway-service/dbrepo.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      dbrepo-analyse-service:
        condition: service_healthy
      dbrepo-authentication-service:
        condition: service_healthy
      dbrepo-broker-service:
        condition: service_healthy
      dbrepo-metadata-service:
        condition: service_healthy
      dbrepo-search-db:
        condition: service_healthy
      dbrepo-ui:
        condition: service_started
    logging:
      driver: json-file

  dbrepo-search-db-dashboard:
    restart: "no"
    container_name: dbrepo-search-db-dashboard
    hostname: search-db-dashboard
    image: docker.io/opensearchproject/opensearch-dashboards:2.10.0
    volumes:
      - ./dbrepo-search-db/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    ports:
      - "5601:5601"
    depends_on:
      dbrepo-search-db:
        condition: service_healthy
    logging:
      driver: json-file

  dbrepo-mirror-service:
    restart: "no"
    container_name: dbrepo-mirror-service
    hostname: mirror-service
    build: ./dbrepo-mirror-service
    image: dbrepo/mirror-service@sha256:5085efebe4c7364ee93a95589ce2dbaa02ee95c409db4466e17a8aabd55f35ca
    ports:
      - "9050:9050"
    environment:
      METADATA_DB: ${METADATA_DB:-fda}
      METADATA_HOST: ${METADATA_HOST:-metadata-db}
      METADATA_JDBC_EXTRA_ARGS: ${METADATA_JDBC_EXTRA_ARGS:-}
      METADATA_PASSWORD: ${METADATA_PASSWORD:-dbrepo}
      METADATA_USERNAME: ${METADATA_USERNAME:-root}
      SEARCH_USERNAME: ${SEARCH_USERNAME:-admin}
      SEARCH_PASSWORD: ${SEARCH_PASSWORD:-admin}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      SYNC_RATE: ${SYNC_RATE:-60000}
    healthcheck:
      test: wget -qO- localhost:9050/actuator/health/readiness | grep -q "UP" || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
    depends_on:
      dbrepo-metadata-db:
        condition: service_healthy
      dbrepo-search-db:
        condition: service_started
    logging:
      driver: json-file

  dbrepo-data-service:
    restart: "no"
    container_name: dbrepo-data-service
    hostname: data-service
    build: ./dbrepo-data-service
    image: dbrepo/data-service@sha256:b4fe582fe8b4ef262db94cda95eb94c64ef73ba0a1c64948b8fb167402e1746e
    ports:
      - "9093:9093"
    environment:
      METADATA_DB: ${METADATA_DB:-fda}
      METADATA_HOST: ${METADATA_HOST:-metadata-db}
      METADATA_JDBC_EXTRA_ARGS: ${METADATA_JDBC_EXTRA_ARGS:-}
      METADATA_PASSWORD: ${METADATA_PASSWORD:-dbrepo}
      METADATA_USERNAME: ${METADATA_USERNAME:-root}
      JWT_ISSUER: "${JWT_ISSUER:-http://localhost/api/auth/realms/dbrepo}"
      JWT_PUBKEY: "${JWT_PUBKEY:-MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqqnHQ2BWWW9vDNLRCcxD++xZg/16oqMo/c1l+lcFEjjAIJjJp/HqrPYU/U9GvquGE6PbVFtTzW1KcKawOW+FJNOA3CGo8Q1TFEfz43B8rZpKsFbJKvQGVv1Z4HaKPvLUm7iMm8Hv91cLduuoWx6Q3DPe2vg13GKKEZe7UFghF+0T9u8EKzA/XqQ0OiICmsmYPbwvf9N3bCKsB/Y10EYmZRb8IhCoV9mmO5TxgWgiuNeCTtNCv2ePYqL/U0WvyGFW0reasIK8eg3KrAUj8DpyOgPOVBn3lBGf+3KFSYi+0bwZbJZWqbC/Xlk20Go1YfeJPRIt7ImxD27R/lNjgDO/MwIDAQAB}"
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      MIN_CONCURRENT_CONSUMERS: ${MIN_CONCURRENT_CONSUMERS:-1}
      MAX_CONCURRENT_CONSUMERS: ${MAX_CONCURRENT_CONSUMERS:-5}
      BROKER_USERNAME: ${BROKER_USERNAME:-fda}
      BROKER_PASSWORD: ${BROKER_PASSWORD:-fda}
      BROKER_HOST: "${BROKER_HOST:-broker-service}"
      BROKER_VIRTUALHOST: ${BROKER_VIRTUALHOST:-dbrepo}
      REQUEUE_REJECTED: ${REQUEUE_REJECTED:-false}
      QUEUE_NAME: ${QUEUE_NAME:-dbrepo}
      EXCHANGE_NAME: ${EXCHANGE_NAME:-dbrepo}
      ROUTING_KEY: "${ROUTING_KEY:-dbrepo.#}"
      CONNECTION_TIMEOUT: ${CONNECTION_TIMEOUT:-60000}
    healthcheck:
      test: wget -qO- localhost:9093/actuator/health/readiness | grep -q "UP" || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
    depends_on:
      dbrepo-metadata-db:
        condition: service_healthy
      dbrepo-data-db:
        condition: service_healthy
    logging:
      driver: json-file